spring: 
    profiles: 
        active: 
        - dev

---

#使用不同profile使用不同服务名称来测试配置版本
spring: 
    profiles: dev
    application: 
        name: springcloud-sgg-config-dev

---

spring: 
    profiles: test
    application: 
        name: springcloud-sgg-config-test