spring: 
  profiles: 
    active: dev
---
spring: 
  profiles: dev
  application: 
    name: springcloud-sgg-config-dev
---
spring: 
  profiles: test
  application: 
    name: springcloud-sgg-config-test